name: Deploy an internal version

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Internal version for testing'
        type: string
        required: true
        default: 'Internal version'
      release_type:
        description: 'select environment <dev | stg>'
        required: true
        type: choice
        options:
          - development
          - staging


jobs:

  deploy:
    name: deploy an internal version to app distribution
    runs-on: ${{ vars.RUNNER }}
    environment: ${{ vars.ENVIRONMENT_STAGE }}
    env:
      JAVA_VERSION: ${{ vars.JAVA_VERSION }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '${{env.JAVA_VERSION}}'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle command - assembleDebug
        run: ./gradlew assembleDebug
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk