name: Tests debug
on:
  workflow_call:
jobs:

  test-debug:
    name: run tests debug variant
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: ${{ vars.JAVA_VERSION }}
    steps:
      - uses: actions/checkout@v4

      - name: JAVA VERSION
        run: echo "JAVA-VERSION - ${{env.JAVA_VERSION}}"

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '${{env.JAVA_VERSION}}'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle command - testDebugUnitTest
        run: ./gradlew testDebugUnitTest