# This is a basic workflow to help you get started with Actions

name: Test CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  lint:
    name: Linting debug variant
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: ${{ vars.JAVA_VERSION }}
    steps:
      - uses: actions/checkout@v4

      - name: JAVA VERSION
        run: echo "JAVA-VERSION - ${{env.JAVA_VERSION}}"

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1

        with:
          distribution: 'temurin'
          java-version: '${{env.JAVA_VERSION}}'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build with Gradle
        run: ./gradlew build

      - name: Execute Gradle command - lintDebug
        run: ./gradle lintDebug